server:
  port: 9006
spring:
  application:
    name: hrm-page
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_page
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath:cn/itsource/hrm/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.hrm.domain,cn.itsource.hrm.query